name-template: 'v$NEXT_PATCH_VERSION 🌟'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐛 Fixes'
    labels: ['fix', 'bug']
  - title: '🛠 Maintenance'
    labels: ['chore', 'refactor']
exclude-labels:
  - 'skip-changelog'