name: Build & Upload Extension

on:
  push:
    branches:
      - main
      - "release/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Build extension
        run: bun run build --filter=magneto

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-build
          path: apps/extension/dist/*.zip
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: extension-build
          path: build-output

      - name: Determine release version
        id: version
        run: |
          ref="${GITHUB_REF#refs/heads/}"
          if [[ "$ref" == "main" ]]; then
            version=$(jq -r .version apps/extension/package.json)
          elif [[ "$ref" == release/* ]]; then
            version="${ref#release/}"
          fi
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          if ! git rev-parse "v${{ steps.version.outputs.version }}" >/dev/null 2>&1; then
            git tag "v${{ steps.version.outputs.version }}"
            git push origin "v${{ steps.version.outputs.version }}"
          fi

      - name: Upload assets to Release (create/update)
        uses: softprops/action-gh-release@v2
        with:
          files: build-output/*.zip
          tag_name: v${{ steps.version.outputs.version }}
          prerelease: ${{ startsWith(github.ref, 'refs/heads/release/') }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
